name = "vectorize-worker"
main = "./vectorize.ts"
compatibility_date = "2024-05-14"

# Custom domain routing
routes = [
  { pattern = "vectorize.blakebauman.dev", custom_domain = true }
]

[ai]
binding = "AI"
model = "@cf/baai/bge-base-en-v1.5"

[ai.embeddings]
binding = "AI_EMBEDDINGS"
model = "@cf/baai/bge-base-en-v1.5"

[[vectorize]]
binding = "VECTORIZE"
index_name = "resume-index-768"

[vars]
VECTORIZE_INDEX = "resume-index-768" 