name = "vectorize-worker"
main = "vectorize.ts"
compatibility_date = "2024-02-14"

[vars]
VECTORIZE_INDEX = "resume-index"
CF_API_TOKEN = ""  # You'll need to set this in your environment

[ai]
binding = "AI"
model = "@cf/baai/bge-base-en-v1.5"

[[vectorize]]
binding = "VECTORIZE"
index_name = "resume-index" 